name: build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: michaelpanderson/check_pull_request_branch@main
     
